DROP DATABASE xxx;
CREATE DATABASE xxx;
USE xxx;

CREATE TABLE clientes (
  id varchar(255) NOT NULL,
  cliente varchar(255) NOT NULL
);
CREATE TABLE contactos (
  id varchar(255) NOT NULL,
  nombre varchar(255) NOT NULL,
  correo varchar(255) NOT NULL
);





INSERT INTO clientes VALUES('0002','ADALBERTO ENRIQUE DUARTE MACDONALD');
INSERT INTO contactos VALUES('0002','ADALBERTO ENRIQUE DUARTE','luisdmc@prodigy.net.mx');
INSERT INTO clientes VALUES('0004','ADHESIVOS Y BOQUILLAS INTERCERAMIC S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0004','INTERCERAMIC CXP','sjurado@interceramic.com');
INSERT INTO contactos VALUES('0004','INTERCERAMIC CXP','kviveros@interceramic.com');
INSERT INTO contactos VALUES('0004','INTERCERAMIC CXP','omendoza@interceramic.com');
INSERT INTO clientes VALUES('0009','AGRI-ESTRELLA S.DE R.L.. DE C.V.');
INSERT INTO contactos VALUES('0009','AGRI-ESTRELLA CXP','jmarquez@agristar.com.mx');
INSERT INTO contactos VALUES('0009','ALFONSO GUTIERREZ','agutierrez@agristar.com.mx');
INSERT INTO clientes VALUES('0013','AGROPECUARIA DEL CONSUELO S.A. DE C.V.');
INSERT INTO contactos VALUES('0013','AGROPECUARIA DEL CONSUELO','mgagropec@hotmail.com');
INSERT INTO clientes VALUES('0018','ALTEC ELECTRONICA CHIHUAHUA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0018','ALTEC CXP','iramirez@visteon.com');
INSERT INTO contactos VALUES('0018','DAVID SILVA CXC','dsilva1@visteon.com');
INSERT INTO contactos VALUES('0018','G VIDAL','gvidal@visteon.com');
INSERT INTO contactos VALUES('0018','MARCELA MUÑOZ','mmunoz3@visteon.com');
INSERT INTO clientes VALUES('0020','AMERICAN BEEF S.A. DE C.V.');
INSERT INTO contactos VALUES('0020','AMERICAN BEEF','oarellanes@amebeef.com');
INSERT INTO contactos VALUES('0020','AMERICAN BEEF','jruiz@amebeef.com');
INSERT INTO clientes VALUES('0030','ARROW INTERNACIONAL DE CHIHUAHUA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0030','ARROW INTERNACIONAL','cinthia.canales@teleflex.com');
INSERT INTO contactos VALUES('0030','CXC','Cinthia.canales@teleflex.com');
INSERT INTO clientes VALUES('0039','BIMBO S.A.  DE C.V.');
INSERT INTO contactos VALUES('0039','BIMBO','francisco.porras@grupobimbo.com');
INSERT INTO clientes VALUES('0042','ROBERT BOSCH SISTEMAS AUTOMOTRICES, S.A. DE C.V.');
INSERT INTO contactos VALUES('0042','CXC','cuentasporpagar@us.bosch.com');
INSERT INTO contactos VALUES('0042','ROBERT BOSCH SISTEMAS AUTOMOTRICES','iveth.holguin@us.bosch.com');
INSERT INTO contactos VALUES('0042','ROBERT BOSCH SISTEMAS AUTOMOTRICES CXP','cuentasporpagarjuarez@us.bosch.com');
INSERT INTO clientes VALUES('0046','BYCOSIN LATINOAMÉRICA S.A. DE C.V.');
INSERT INTO contactos VALUES('0046','BYCOSIN','gruiz@bycosin.com.mx');
INSERT INTO clientes VALUES('0054','CENTRO DE CALIDAD AMBIENTALS.C.');
INSERT INTO contactos VALUES('0054','CENTRO DE CALIDAD AMBIENTAL','lgarcia@ccambiental.com');
INSERT INTO clientes VALUES('0055','CENTRO DE INVESTIGACION EN ALIMENTACION Y DESARROLLO A.C.');
INSERT INTO contactos VALUES('0055','CENTRO DE INVESTIGACION EN ALIMENTOS','ecardona@ciad.mx');
INSERT INTO clientes VALUES('0057','CENTRO DE INGENIERIA Y DESARROLLO INDUSTRIAL');
INSERT INTO contactos VALUES('0057','CENTRO DE INGENIERIA','facturacion.electronica@cidesi.mx');
INSERT INTO contactos VALUES('0057','CENTRO DE INGENIERIA','thernandez@cidesi.mx');
INSERT INTO clientes VALUES('0084','CREST, S.A. DE C.V.');
INSERT INTO contactos VALUES('0084','CIMAV (HONORIO)','honorio.lara@cimav.edu.mx');
INSERT INTO contactos VALUES('0084','CREST','iamaya@crest.com.mx');
INSERT INTO clientes VALUES('0085','CRONI, S.A. DE C.V.');
INSERT INTO contactos VALUES('0085','CRONI CXP','mlopez@ccroni.com');
INSERT INTO clientes VALUES('0090','DANIEL MEASUREMENT AND CONTROL S DE RL DE C.V.');
INSERT INTO contactos VALUES('0090','CXP','fe@informap.mx');
INSERT INTO contactos VALUES('0090','CXP','nayeli.aguirre@emerson.com');
INSERT INTO contactos VALUES('0090','CXP','Sylvia.Almaraz@emerson.com');
INSERT INTO contactos VALUES('0090','DANIEL CXP','daniel.accountspayable-chi@emersonprocess.com');
INSERT INTO contactos VALUES('0090','EDUARDO GONZALEZ','eduardo.gonzalez@emerson.com');
INSERT INTO clientes VALUES('0092','DELMEX DE JUAREZ, S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0092','DELMEX','jorge.garciayala@valeo.com');
INSERT INTO clientes VALUES('0093','DELPHI AUTOMOTIVE SYSTEMS, S.A. DE C.V.');
INSERT INTO contactos VALUES('0093','DELPHI AUTOMOTIVE SYSTEMS','delphia.cuentasporpagar.facturacionelectronica');
INSERT INTO clientes VALUES('0106','ELECTROLUX HOME PRODUCTS DE MEXICO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0106','ELECTROLUX CXP','erika.fernandez@electrolux.com');
INSERT INTO contactos VALUES('0106','ELECTROLUX CXP','jose.hernandez-ortiz@electrolux.com');
INSERT INTO clientes VALUES('0122','FORD MOTOR COMPANY., S.A. DE C.V.');
INSERT INTO contactos VALUES('0122','FORD MOTOR','dgarci76@ford.com');
INSERT INTO contactos VALUES('0122','JUAN AGUIRRE','jaguirre@ford.com');
INSERT INTO clientes VALUES('0124','FOXCONN MEXICO PRECISION INDUSTRY CO. S.A. DE C.V.');
INSERT INTO contactos VALUES('0124','FOXCONN','ulises.lopez@foxconn.com');
INSERT INTO contactos VALUES('0124','FOXCONN','marco.mondragon@foxconn.com');
INSERT INTO contactos VALUES('0124','FOXCONN MEXICO PRECISION INDUSTRY','jessica.villalobos@foxconn.com');
INSERT INTO clientes VALUES('0125','FR TECNOLOGIAS DE FLUJO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0125','FR TECNOLOGIAS DE FLUJO','miguel.ortega@emerson.com');
INSERT INTO contactos VALUES('0125','FR TECNOLOGIAS DE FLUJO CXP','Facturacion.tf@emerson.com');
INSERT INTO clientes VALUES('0130','FWF DE MEXICO, S. DE .R.L. DE C.V.');
INSERT INTO contactos VALUES('0130','FWF','f.mora@fwf-de-mexico.com');
INSERT INTO contactos VALUES('0130','FWF','r.perez@fwf-de-mexico.com');
INSERT INTO contactos VALUES('0130','FWF','fwm_facturas@fwf-de-mexico.com');
INSERT INTO clientes VALUES('0132','GAMMON LAKE DE MEXICO, S.A. DE C.V');
INSERT INTO contactos VALUES('0132','GAMMON LAKE CXP','gparedes@gammonlake.com');
INSERT INTO contactos VALUES('0132','GAMMON LAKE CXP','kperez@gammonlake.com');
INSERT INTO clientes VALUES('0134','GCC CEMENTO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0134','GCC CEMENTO','ivalenzu@gcc.com');
INSERT INTO contactos VALUES('0134','GCC CXC','strejome@gcc.com');
INSERT INTO clientes VALUES('0135','GCC CONCRETO S.A. DE C.V.');
INSERT INTO contactos VALUES('0135','GCC','oalvarado@gcc.com');
INSERT INTO contactos VALUES('0135','GCC CONCRETO','mromero@gcc.com');
INSERT INTO contactos VALUES('0135','GCC CONCRETO','chernandezg@gcc.com');
INSERT INTO clientes VALUES('0144','GRUPO AMERICAN INDUSTRIES, S.A.DE C.V.');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN  (SOUTHCO)','bnava@southco.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN  ITT','cacosta@aiig.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (AMFUEL)','aviramontes@aiig.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (ARNPRIOR AEROSPACE)','jorge.arias@arnprioraerospace.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (DTR)','ltarango@aiig.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (ICORE)','mfranco@aiig.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (ICORE)','aviramontes@aiig.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (ICORE)','igmar.reyes@zodiacaerospace.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (SOUTHCO)','egrajeda@aiig.com');
INSERT INTO contactos VALUES('0144','GRUPO AMERICAN (ZODIAC AEROSPACE) CXC','kgardea@aiig.com.');
INSERT INTO contactos VALUES('0144','GRUPOA AMERICAN CAV AEROSPACE','sreyes@aiig.com');
INSERT INTO contactos VALUES('0144','KAREN GARDEA CXP (WEBER)','kgardea@aiig.com');
INSERT INTO contactos VALUES('0144','MAYRA RUIZ CXP(WEBER)','mruiz@aiig.com');
INSERT INTO contactos VALUES('0144','MIGUEL GALAZ','mgalaz@dtrmx.com');
INSERT INTO contactos VALUES('0144','PAULINA QUEZADA (NORDAM)','pquezada@nordam.com');
INSERT INTO clientes VALUES('0148','GRUPO TECNICO EN CONSTRUCCION CAYSA S.A. DE C.V.');
INSERT INTO contactos VALUES('0148','GRUPO TECNICO EN COSTRUCCION CAYSA','caysa92@prodigy.net.mx');
INSERT INTO clientes VALUES('0151','HARINAS DE CHIHUAHUA S.A. DE C.V.');
INSERT INTO contactos VALUES('0151','HARINAS DE CHIHUAHUA','rvidal@grupoharinas.com.mx');
INSERT INTO clientes VALUES('0152','MAXION WHEELS DE MÉXICO S. DE R.L. DE C.V');
INSERT INTO contactos VALUES('0152','HAYES LEMMERZ ALUMINIO','esalazar@hayes_lemmerz.com');
INSERT INTO clientes VALUES('0154','HONEYWELL MANUFACTURAS DE CHIHUAHUA. S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0154','HONEYWELL MANUFACTURAS CXP','heber.saavedra@honeywell.com');
INSERT INTO clientes VALUES('0170','INSTALACIONES Y MAQUINARIA  INMAQ SA. DE C.V.');
INSERT INTO contactos VALUES('0170','INSTALACIONES Y MAQUINARIA INMAQ','gcolmenero@bafar.com.mx');
INSERT INTO clientes VALUES('0175','INTERMEX MANUFACTURA DE CHIHUAHUA, S.A DE C.V');
INSERT INTO contactos VALUES('0175','INTERMEX MANUFACTURA DE CHIHUAHUA','recepcion_cfd_shelter@intermex.com');
INSERT INTO clientes VALUES('0176','INTERNACIONAL DE CERAMICA, S.A.B. DE C.V.');
INSERT INTO contactos VALUES('0176','INTERCERAMIC CXP','SJURADO@INTERCERAMIC.COM');
INSERT INTO contactos VALUES('0176','INTERCERAMIC CXP','kviveros@interceramic.com');
INSERT INTO contactos VALUES('0176','INTERCERAMIC CXP','omendoza@interceramic.com');
INSERT INTO clientes VALUES('0183','JABIL CIRCUIT DE CHIHUAHUA, S. DE R.L. DE C.V..');
INSERT INTO contactos VALUES('0183','CRISTINA ZUNIGA CXC','cristina_zuniga2@jabil.com');
INSERT INTO contactos VALUES('0183','JABIL','hugo_venzoresespinoza@jabil.com');
INSERT INTO contactos VALUES('0183','JABIL CXC','jabilcuuinvoices@jabil.com');
INSERT INTO contactos VALUES('0183','MAYRA IBARRA CXC','mayra_ibarra@jabil.com');
INSERT INTO clientes VALUES('0193','JOSE ENRIQUE CASTAÑEDA RODRIGUEZ.');
INSERT INTO contactos VALUES('0193','JOSE ENRIQUES CASTAÑEDA','vero@basculasdechihuahua.com');
INSERT INTO contactos VALUES('0193','JOSE ENRIQUES CASTAÑEDA','jose@basculasdechihuahua');
INSERT INTO clientes VALUES('0196','JUGOMEX S.A. DE C.V.');
INSERT INTO contactos VALUES('0196','ITZEL CORRAL','icorral@jumex.com.mx');
INSERT INTO clientes VALUES('0203','LABINAL DE MEXICO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0203','COMPRAS','compras.planta1@mx.labinal.com');
INSERT INTO contactos VALUES('0203','LABINAL','practicante.compras@mx.labinal.com');
INSERT INTO contactos VALUES('0203','LABINAL CXP','LCI9710149W6@buzonfiscal.com');
INSERT INTO contactos VALUES('0203','LABINAL CXP','diana.quezada@mx.labinal.com');
INSERT INTO clientes VALUES('0205','LABORATORIO Y CONSULTORIA S.A. DE C.V');
INSERT INTO contactos VALUES('0205','LABORATORIO Y CONSULTORIA','mcorral@lacosachih.net');
INSERT INTO contactos VALUES('0205','LABORATORIO Y CONSULTORIA','lacosachih@prodigy.net.mx');
INSERT INTO contactos VALUES('0205','LABORATORIO Y CONSULTORIA FACTURAS','comprobantesfiscales@lacosachih.net');
INSERT INTO clientes VALUES('0206','LABORATORIO DE ESTUDIOS INTEGRALES DE CD JUAREZ, S. C.');
INSERT INTO contactos VALUES('0206','LABORATORIO','jchacon@leisajuarez.net');
INSERT INTO contactos VALUES('0206','LABORATORIO Y ESTUDIOS INTEGRALES','lramirez@leisajuarez.net');
INSERT INTO clientes VALUES('0210','LEONI CABLE S.A. DE C.V.');
INSERT INTO contactos VALUES('0210','LEONI CABLE','johana.rascon@leoni.com');
INSERT INTO contactos VALUES('0210','LEONI CABLE','adrian.delgado@leoni.com');
INSERT INTO clientes VALUES('0221','MANUFACTURAS ESTAMPADAS, S.A. DE C.V.');
INSERT INTO contactos VALUES('0221','MANUFACTURAS ESTAMPADAS','cvidana@manesa.com');
INSERT INTO clientes VALUES('0222','MANUFACTURAS VITROMEX, S..A DE C.V.');
INSERT INTO contactos VALUES('0222','MANUFACTURAS VITROMEX','linda.martinezl@gis.com.mx');
INSERT INTO contactos VALUES('0222','MANUFACTURAS VITROMEX','jose.montoyab@gis.com.mx');
INSERT INTO contactos VALUES('0222','MANUFACTURAS VITROMEX','perla.robledo@gis.com');
INSERT INTO clientes VALUES('0233','MELENDEZ  PIZARRO SALVADOR');
INSERT INTO contactos VALUES('0233','CXC','cysasa10@gmail.com');
INSERT INTO clientes VALUES('0237','MINERALES METALICOS DEL NORTE, S.A.');
INSERT INTO contactos VALUES('0237','MINERALES METALICOS CXP','recepcion.facturacionelectronica@gmexico.com');
INSERT INTO clientes VALUES('0239','MOLINOS ANAHUAC, SA. DE C.V.');
INSERT INTO contactos VALUES('0239','ING. CARLOS CALVILLO','0446141844717');
INSERT INTO contactos VALUES('0239','MOLINOS ANAHUAC','betimacsa@hotmail.com');
INSERT INTO clientes VALUES('0258','PACE INDUSTRIES DE CHIHUAHUA II, S.A DE C.V.');
INSERT INTO contactos VALUES('0258','SALVADOR LARIOS','salvador.larios@paceind.com');
INSERT INTO clientes VALUES('0259','PAPELERA DE CHIHUAHUA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0259','JUAN CARRILLO','Juana.carrillo@copamex.com');
INSERT INTO contactos VALUES('0259','JUAN SOTELO','juan.m.sotelo@copamex.com');
INSERT INTO contactos VALUES('0259','PAPELERA','aurora.terrazas@copamex.com');
INSERT INTO clientes VALUES('0269','PONDERCEL S.A. DE C.V.');
INSERT INTO contactos VALUES('0269','PONDERCEL','pablo.lara@copamex.com');
INSERT INTO contactos VALUES('0269','PONDERCEL','juan.cruz@copamex.com');
INSERT INTO contactos VALUES('0269','PONDERCEL','marco.soto@copamex.com');
INSERT INTO contactos VALUES('0269','PONDERCEL','luis.carmona@copamex.com');
INSERT INTO clientes VALUES('0282','PRODUCTOS QUIMICOS DE CHIHUAHUA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0282','CINDY AGUIRRE CXP','cindyaguirre@innovakglobal.com');
INSERT INTO contactos VALUES('0282','PRODUCTOS QUIMICOS','jsalcido@innovakglobal.com');
INSERT INTO contactos VALUES('0282','PRODUCTOS QUIMICOS DE CHIHUAUA','ffranco@innovakglobal.com');
INSERT INTO clientes VALUES('0290','RECUBRIMIENTOS INTERCERAMIC, S.A. DE C.V.');
INSERT INTO contactos VALUES('0290','INTERCERAMIC CXP','sjurado@interceramic.com');
INSERT INTO contactos VALUES('0290','INTERCERAMIC CXP','kviveros@interceramic.com');
INSERT INTO contactos VALUES('0290','INTERCERAMIC CXP','omendoza@interceramic.com');
INSERT INTO clientes VALUES('0301','SERVICIO GEOLOGICO MEXICANO');
INSERT INTO contactos VALUES('0301','LUCERO','ldlucero@sgm.gob.mx');
INSERT INTO clientes VALUES('0311','SIGMA ALIMENTOS NORESTE, S.A. DE C.V.');
INSERT INTO contactos VALUES('0311','MARCELA MALDONADO','marmaldona@sigma-alimentos.com');
INSERT INTO clientes VALUES('0315','SMTC DE CHIHUAHUA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0315','SMTC DE CHIHUAHUA','gisela.melendez@smtc.com');
INSERT INTO clientes VALUES('0316','SOFI DE CHIHUAHUA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0316','CXP','sacosta@essilorusa.com');
INSERT INTO clientes VALUES('0322','SUPERIOR INDUSTRIES DE MÉXICO, S. DE R.L DE C.V');
INSERT INTO contactos VALUES('0322','CXC','iterraza@supind.com');
INSERT INTO contactos VALUES('0322','KEVIN ANCHONDO CXP','kanchond@supind.com');
INSERT INTO contactos VALUES('0322','PABLO PASILLAS CXP','Ppasilla@supind.com');
INSERT INTO contactos VALUES('0322','SILVIA OCHOA','sochoa@supind.com');
INSERT INTO clientes VALUES('0324','TECNOLOGIA AMBIENTAL E INGENIERÍA, S.A DE C.V.');
INSERT INTO contactos VALUES('0324','TECNOLOGIA AMBIENTAL','laboratorio@tecnologiaamb.com');
INSERT INTO clientes VALUES('0326','TERMOTEC DE CHIHUAHUA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0326','TERMOTEC','enrique.soto@emerson.com');
INSERT INTO contactos VALUES('0326','VIVIANA BENCOMO','viviana.bencomo@emerson.com');
INSERT INTO clientes VALUES('0329','TRW STEERING WHEEL SYSTEMS DE CHIHUAHUA, S.A DE C.V.');
INSERT INTO contactos VALUES('0329','TRW STEERING WHEEL CXP','ivonne.saenz@trw.com');
INSERT INTO clientes VALUES('0338','VISTEON DE MEXICO S DE RL');
INSERT INTO contactos VALUES('0338','GAUDENCIO VIDAL','gvidal@visteon.com');
INSERT INTO contactos VALUES('0338','MARCELA MUÑOZ','mmunoz3@visteon.com');
INSERT INTO contactos VALUES('0338','VISTEON','cvillas2@visteon.com');
INSERT INTO clientes VALUES('0340','VTC WEST S.A. DE C.V.');
INSERT INTO contactos VALUES('0340','VTC WEST','buzon_facturas@vatransformer.com');
INSERT INTO clientes VALUES('0357','LEVITON DE MEXICO, S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0357','LEVITON','khernandez@leviton.com');
INSERT INTO contactos VALUES('0357','LEVITON','mmedina@leviton.com');
INSERT INTO contactos VALUES('0357','LEVITON','nfernandez@leviton.com');
INSERT INTO clientes VALUES('0375','SECRETARIA DE EDUCACION PUBLICA');
INSERT INTO contactos VALUES('0375','SEP','compras@crodechihuahua.edu.mx');
INSERT INTO clientes VALUES('0377','GCC CONCRETO S.A. DE C.V.');
INSERT INTO contactos VALUES('0377','JESUS GARCIA','jgarciahdez@gcc.com');
INSERT INTO clientes VALUES('0386','TIENDAS SORIANA S.A DE C.V.');
INSERT INTO contactos VALUES('0386','TIENDAS SORIANA','cinternos586@soriana.com');
INSERT INTO clientes VALUES('0395','QUIMICA AGRONOMICA DE MEXICO, S. DE R.L. M.I.');
INSERT INTO contactos VALUES('0395','NATALIA ORTIZ','nortiz@qam.com.mx');
INSERT INTO clientes VALUES('0403','SERVICIOS DE SALUD DE CHIHUAHUA');
INSERT INTO contactos VALUES('0403','DENISSE CHAPARRO','d.chaparro@chihuahua.gob.mx');
INSERT INTO clientes VALUES('0405','LEVITON DE MEXICO, S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0405','LEVITON DE MEXICO','mmedina@leviton.com');
INSERT INTO contactos VALUES('0405','LEVITON DE MEXICO','nfernandez@leviton.com');
INSERT INTO contactos VALUES('0405','LEVITON DE MEXICO','khernandez@leviton.com');
INSERT INTO clientes VALUES('0409','MACDERMID MÉXICO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0409','MACDERMIND','gsantiago@macdermid.com.mx');
INSERT INTO clientes VALUES('0416','UNIVERSIDAD AUTONOMA DE SINALOA');
INSERT INTO contactos VALUES('0416','JESUS ADRIAN BALDENEBRA UNI AUT DE SINAL','jabaldenebro@hotmail.com');
INSERT INTO clientes VALUES('0421','COMPAÑIA MINERA DOLORES, S.A DE C.V');
INSERT INTO contactos VALUES('0421','COMPAÑIA MINERA DE DOLORES','alopez@cmdolores.com');
INSERT INTO clientes VALUES('0428','GRUPO COMERCIAL DE MÉXICO S.A. DE C.V.');
INSERT INTO contactos VALUES('0428','COMBUSTIBLES MTY','bdomingu@nieto.com.mx');
INSERT INTO clientes VALUES('0432','HONEYWELL OPTOELECTRÓNICA S DE R.L DE C.V.');
INSERT INTO contactos VALUES('0432','BLANCA URIBE CXP','Blanca.uribe@Honeywell.com');
INSERT INTO contactos VALUES('0432','CXP','cuentasxpagarmx03@honeywell.com');
INSERT INTO clientes VALUES('0434','QUESERIA DOS LAGUNAS, S.PR DE R.L DE C.V');
INSERT INTO contactos VALUES('0434','QUESEERIA DOS LAGUNAS','erios@qdl.com.mx');
INSERT INTO clientes VALUES('0439','INDUSTRIAS SELKIRK DE MÉXICO S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0439','INDUSTRIAS SELKIRK','jpando@selkirkcorp.com');
INSERT INTO contactos VALUES('0439','INDUSTRIAS SELKIRK','acervantes@selkirkcorp.com');
INSERT INTO contactos VALUES('0439','INDUSTRIAS SELKIRK','eproano@selkirkcorp.com');
INSERT INTO clientes VALUES('0490','COMITÉ ESTATAL DE FOMENTO Y PROTECCIÓN PECUARIA DE CHIHUAHUA A.C.');
INSERT INTO contactos VALUES('0490','CUENTAS POR PAGAR','cedisach_recepcion@prodigy.net.mx');
INSERT INTO clientes VALUES('0500','LUTRON CNC S. DE R.L DE C.V.');
INSERT INTO contactos VALUES('0500','LUTRON','jlmunoz@lutron.com');
INSERT INTO contactos VALUES('0500','LUTRON CNC','sreaza@lutron.com');
INSERT INTO clientes VALUES('0508','PRODUCTOS QUÍMICOS AR. S.A. DE C.V.');
INSERT INTO contactos VALUES('0508','PRODUCTOS QUIMICOS AR','proquimar@yahoo.com.mx');
INSERT INTO contactos VALUES('0508','PRODUCTOS QUMICOS AR','ffranco@innovakglobal.com');
INSERT INTO clientes VALUES('0512','INTERMETRO DE MÉXICO, S. DE R.L. DE C.V');
INSERT INTO contactos VALUES('0512','CUENTAS POR PAGAR (COMPRAS)','vera.alarcon@emerson.com');
INSERT INTO contactos VALUES('0512','INTERMETRO CXP','minca.varela.grijalva@emerson.com');
INSERT INTO contactos VALUES('0512','INTERMETRO CXP','jesus.grijalva@emerson.com');
INSERT INTO contactos VALUES('0512','PASCUAL SINALOA','pascual.sinaloa@emerson.com');
INSERT INTO clientes VALUES('0537','ESJ S.A. DE C.V.');
INSERT INTO contactos VALUES('0537','ESJ','sbaca@esjoist.com');
INSERT INTO clientes VALUES('0553','UNIVERSIDAD AUTONOMA DE CD. JUAREZ CHIHUAHUA');
INSERT INTO contactos VALUES('0553','UACJ','abarel14@yahoo.com.mx');
INSERT INTO clientes VALUES('0563','DURAPLAY DE PARRAL S.A DE C.V.');
INSERT INTO contactos VALUES('0563','SERGIO MORALES','sergiomorales@duraplay.com.mx');
INSERT INTO clientes VALUES('0568','BRP MÉXICO S.A. DE C.V.');
INSERT INTO contactos VALUES('0568','BRP CXP','dena.ruiz@brp.com');
INSERT INTO clientes VALUES('0579','PLACOSA, S.A. DE C.V');
INSERT INTO contactos VALUES('0579','PLACOSA','dolores_arias@placosanet.com');
INSERT INTO contactos VALUES('0579','PLACOSA','marco_antonio@placosanet.com');
INSERT INTO clientes VALUES('0591','INJECTION ALLOYS MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('0591','INJECTIONALLOYS','Jazmin.jacobo@injectionalloys.com');
INSERT INTO clientes VALUES('0593','AGROPECUARIA LA NORTEÑITA S. DE R.L. DE C.V');
INSERT INTO contactos VALUES('0593','AGROPECUARIA LA NORTEÑITA','irisgonzalez@gpoln.com');
INSERT INTO contactos VALUES('0593','AGRPECUARIA LA NORTEÑITA','cecilialechuga@gpoln.com');
INSERT INTO clientes VALUES('0595','AIR TEMP DE MÉXICO, S.A DE C.V.');
INSERT INTO contactos VALUES('0595','AIR TEMP','leticia@airtemp.com.mx');
INSERT INTO clientes VALUES('0599','INDUSTRIAS PROMI DE OCCIDENTE, S.A DE C.V');
INSERT INTO contactos VALUES('0599','INDUSTRIAS PROMI','calidadsilica@promi.com.mx');
INSERT INTO contactos VALUES('0599','INDUSTRIAS PROMI','contabilidad@promi.com.mx');
INSERT INTO contactos VALUES('0599','INDUSTRIAS PROMI','auxiliarcontable@promi.com.mx');
INSERT INTO contactos VALUES('0599','INDUSTRIAS PROMI','desarrollosilica@promi.com.mx');
INSERT INTO clientes VALUES('0602','HONEYWELL AEROSPACE DE MEXICO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0602','CXP','CXP_AERO_HCMO@honeywell.com');
INSERT INTO clientes VALUES('0612','MINAS SANTA MARÍA DE MORIS, S.A DE C.V');
INSERT INTO contactos VALUES('0612','MINAS SANTA MARIA DE MORIS','daniel.juarez@hocplc.com');
INSERT INTO clientes VALUES('0644','TED DE MÉXICO, S.A DE C.V.');
INSERT INTO contactos VALUES('0644','TED DE MEXICO','violeta.alvarado@stoneridge.com');
INSERT INTO clientes VALUES('0657','GLOBAL PRODUCTS S.A DE C.V');
INSERT INTO contactos VALUES('0657','GLOBAL PRODUCTS','cynthia.valdez@batesville.com');
INSERT INTO clientes VALUES('0662','DIA BRAS MEXICANA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0662','DIA BRAS MEXICANA','rterrazas@diabras.com');
INSERT INTO clientes VALUES('0664','IDEA, S.A DE C.V.');
INSERT INTO contactos VALUES('0664','IDEA SA DE CV','alejandro@idea.com.mx');
INSERT INTO clientes VALUES('0672','FRUTÍCOLA PICO LARGO, S. DE R.L M.I');
INSERT INTO contactos VALUES('0672','GUADALUPE RUACHO','calidad@picolargo.com');
INSERT INTO clientes VALUES('0675','AGNICO EAGLE MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('0675','LUIS MUÑOZ','lmunoz@agnico-eagle.com');
INSERT INTO clientes VALUES('0676','ADRIANA FRESCAS GARCÍA');
INSERT INTO contactos VALUES('0676','ADRIANA FRESCAS','adren16@hotmail.com');
INSERT INTO clientes VALUES('0677','CID CENTRO DE INVESTIGACIÓN Y DESARROLLO TECNOLÓGICO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0677','ALBERTO ROSAS','alberto.rosas@desc.com.mx');
INSERT INTO clientes VALUES('0678','CONTINENTAL AUTOMOTIVE GUADALAJARA MÉXICO, S.A DE C.V.');
INSERT INTO contactos VALUES('0678','EDUARDO BARRIGA','eduardo.barriga@continental-corporation.com');
INSERT INTO contactos VALUES('0678','ROCIO GONZÁLEZ','rocio.gonzalez@siemens.com');
INSERT INTO clientes VALUES('0679','BOURNS DE MÉXICO, S. DE R.L DE C.V');
INSERT INTO contactos VALUES('0679','BOURNS DE MEXICO','ignacio.pacheco@bourns.com');
INSERT INTO contactos VALUES('0679','BOURNS DE MEXICO','acounts.payablechih@bourns.com');
INSERT INTO contactos VALUES('0679','BOURNS DE MEXICO','edgar.dominguez@bourns.com');
INSERT INTO clientes VALUES('0685','EPIC TECHNOLOGIES DE JUÁREZ S DE R.L DE C.V');
INSERT INTO contactos VALUES('0685','RIGOBERTO TERRY','rigoberto.terry@epictech.com');
INSERT INTO clientes VALUES('0695','FRANCISCO JAVIER TERRAZAS SALCIDO');
INSERT INTO contactos VALUES('0695','FRANCISCO TERRAZAS','uvseie_188_a@hotmail.com');
INSERT INTO clientes VALUES('0698','GR SPRING & STAMPING DE MEXICO, S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0698','GR SPRING CXP','cuquisduran@grss-mx.com');
INSERT INTO clientes VALUES('0700','MAGNESIUM ALUMINUM DE MÉXICO S. DE R.L DE C.V');
INSERT INTO contactos VALUES('0700','JORGE ARIAS','jarias@magalumcorp.com.mx');
INSERT INTO clientes VALUES('0704','PERMONT CONSTRUCTORA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0704','PERMONT','permont96@yahoo.com.mx');
INSERT INTO clientes VALUES('0724','GASTÓN ELADIO OLVERA SANABRIA');
INSERT INTO contactos VALUES('0724','GASTÓN OLVERA','gaston_olvera@usa.net');
INSERT INTO clientes VALUES('0725','HOUGHTON METAL FINISHING MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('0725','HOUGHTON METAL','mdurstewitz@houghtonintl.com');
INSERT INTO contactos VALUES('0725','JOHN OLSON','jolson@houghtonintl.com');
INSERT INTO clientes VALUES('0733','SERVICIO Y ASESORÍA ELÉCTRICA DELTA, S.A DE C.V');
INSERT INTO contactos VALUES('0733','FRANCISCO JAVIER TERRAZAS SALCIDO','UVSEIE_188_A@HOTMAIL.COM');
INSERT INTO clientes VALUES('0744','MABE S.A. DE C.V.');
INSERT INTO contactos VALUES('0744','CXC','facturacion.electronica@mabe.com.mx');
INSERT INTO contactos VALUES('0744','MARIA DE LOS ANGELES CALIXTO','Maria_Angeles.Calixto@mabe.com.mx');
INSERT INTO clientes VALUES('0771','MET-MEX, PEÑOLES SA DE CV');
INSERT INTO contactos VALUES('0771','GRISELDA RANGEL','griselda_rangel@penoles.com.mx');
INSERT INTO contactos VALUES('0771','MET- MEX PEÑOLES','ap_tr@penoles.com.mx');
INSERT INTO clientes VALUES('0781','CENTRO DE INVESTIGACION EN QUIMICA APLICADA');
INSERT INTO contactos VALUES('0781','CENTRO DE INVESTIGACION EN QUIMICA APLIC','jcisnero@ciqa.mx');
INSERT INTO clientes VALUES('0799','IDEA SERVICIOS ADMINISTRATIVOS SA DE CV');
INSERT INTO contactos VALUES('0799','ISA DTR','ltarango@aiig.com');
INSERT INTO contactos VALUES('0799','ISA DTR','mgalaz@dtrmx.com');
INSERT INTO clientes VALUES('0800','CONSULTORES ESPECIALISTAS EN MICROBIOLOGÍA ALIMENTARIA, S. DE RL MI');
INSERT INTO contactos VALUES('0800','CONSULTORES ESPECIALISTAS','espmicrobiol@hotmail.com');
INSERT INTO clientes VALUES('0802','ECOGAS MÉXICO S. DE R.L DE C.V');
INSERT INTO contactos VALUES('0802','ESTHER BOLIVAR','ebolivar@sempraglobal.com');
INSERT INTO clientes VALUES('0817','SOLDADURA DE MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('0817','CXP','ymendoza@soldadura.com');
INSERT INTO clientes VALUES('0829','AGNICO EAGLE MÉXICO, S.A. DE C.V.');
INSERT INTO contactos VALUES('0829','MERLING GRIJALVA','merlyng.grijalva@agnico-eagle.com');
INSERT INTO clientes VALUES('0831','ZF ELECTRONIC SYSTEMS JUÁREZ S.A. DE C.V.');
INSERT INTO contactos VALUES('0831','MARTIN MORALES','martin.morales@zf.com');
INSERT INTO clientes VALUES('0834','TIGHITCO LATINOAMÉRICA, S.A DE C.V');
INSERT INTO contactos VALUES('0834','CESAR MEDINA','cesar.medina@tighitco.com.mx');
INSERT INTO clientes VALUES('0852','CENTRO DE LIDERAZGO Y DESARROLLO HUMANO, A.C.');
INSERT INTO contactos VALUES('0852','ING. DIANA GONZÁLEZ LÓPEZ','diana.gonzalez@chihuahua.semarnat.gob.mx');
INSERT INTO clientes VALUES('0854','DIVERSEY MÉXICO S.A DE C.V');
INSERT INTO contactos VALUES('0854','COMPRAS','cynthia.yos@diversey.com');
INSERT INTO contactos VALUES('0854','COMPRAS','marco.delamora@diversey.com');
INSERT INTO contactos VALUES('0854','CXP','julia.martinez@diversey.com');
INSERT INTO clientes VALUES('0860','HEINRICHS LOERA GUILLERMO EDUARDO');
INSERT INTO contactos VALUES('0860','HEINRICHS LOERA','heinrichshigieneindustrial@gmail.com');
INSERT INTO clientes VALUES('0862','CORDOVA Y ASOCIADOS CAF, S.A DE C.V');
INSERT INTO contactos VALUES('0862','CORDOVA Y ASOCIADOS CAF','cordovayas@prodigy.net.mx');
INSERT INTO clientes VALUES('0865','LEONEL HERNANDEZ HERNANDEZ');
INSERT INTO contactos VALUES('0865','LEONEL HERNANDEZ','leonelhz@prodigy.net.mx');
INSERT INTO clientes VALUES('0870','HONEYWELL AEROSPACE DE MEXICO S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('0870','HONEYWELL AEROSPACE CXP','nohemi.leal@honeywell.com');
INSERT INTO contactos VALUES('0870','HONEYWELL AEROSPACE CXP','cxp_aero_hcmo@honeywell.com');
INSERT INTO clientes VALUES('0871','COMISIÓN MÉXICO-ESTADOS UNIDOS PARA LA PREVENCIÓN DE LA FIEBRE AFTOSA');
INSERT INTO contactos VALUES('0871','COMISION MEXICO-ESTADOS UNIDOS','cpachih@yahoo.es');
INSERT INTO clientes VALUES('0909','JUAN FRANCISCO PONCE LERMA');
INSERT INTO contactos VALUES('0909','JUAN FRANCISCO PONCE','ideacj@prodigy.net.mx');
INSERT INTO clientes VALUES('0920','ZIRA CONSULTORES, S.C');
INSERT INTO contactos VALUES('0920','ARIEL LOYA','ariel.loya@zira.com.mx');
INSERT INTO clientes VALUES('0926','PYMSA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0926','PYMSA','laurapymsa@hotmail.com');
INSERT INTO clientes VALUES('0931','COCLISA, S.A. DE C.V.');
INSERT INTO contactos VALUES('0931','GAUDENCIO VIDAL','gvidal@visteon.com');
INSERT INTO contactos VALUES('0931','MARCELA MUÑOZ','mmunoz3@visteon.com');
INSERT INTO clientes VALUES('0933','VITRO VIDRIO Y CRISTAL SA DE CV');
INSERT INTO contactos VALUES('0933','DRA. ZOULFIA NAGAMEDIANOVA','znagamedianova@vitro.com');
INSERT INTO contactos VALUES('0933','VITRO VIDRIO','asolis@vitro.com');
INSERT INTO clientes VALUES('0941','SERVICIOS AMBIOTRAT S.A. DE C.V.');
INSERT INTO contactos VALUES('0941','SERVICIOS AMBIOTRAT','finanzas@serviciosambiotrat.com.mx');
INSERT INTO clientes VALUES('0954','UNIVERSIDAD JUÁREZ DEL ESTADO DE DURANGO');
INSERT INTO contactos VALUES('0954','DR. EDGAR LOPEZ','chipresche@gmail.com');
INSERT INTO clientes VALUES('0963','FONDO INSTITUCIONAL DEL CONACYT (FOINS)');
INSERT INTO contactos VALUES('0963','RIVERA','jrivera@conacyt.mx');
INSERT INTO contactos VALUES('0963','ROMERO','cromero@conacyt.mx');
INSERT INTO clientes VALUES('0968','CUMMINS GRUPO INDUSTRIAL S. DE R. L DE C.V.');
INSERT INTO contactos VALUES('0968','CUMMINS JUAREZ','veronica.gonzalez@cummins.com');
INSERT INTO contactos VALUES('0968','CUMMINS JUAREZ','flor.valverde@cummins.com');
INSERT INTO clientes VALUES('0978','SUJETADORES DE ACERO S.A DE C.V');
INSERT INTO contactos VALUES('0978','SUJETADORES DE ACERO','franciscogranados@sujetadoresdeacero.com');
INSERT INTO clientes VALUES('0979','ELECTRO COMPONENTES DE MEXICO S.A. DE C.V.');
INSERT INTO contactos VALUES('0979','ELECTRO COMPONENTES','perla.bravo@ecintl.com');
INSERT INTO contactos VALUES('0979','ELECTRO COMPONENTES','rita.chavez@ecintl.com');
INSERT INTO contactos VALUES('0979','ELECTRO COMPONENTES','francisca.ramirez@ecintl.com');
INSERT INTO clientes VALUES('0990','EMYCSA S.A DE C.V');
INSERT INTO contactos VALUES('0990','EMYCSA','avalenzuela@emycsa.com');
INSERT INTO clientes VALUES('0992','COLUMBUS INDUSTRIES MÉXICO S. DE R.L DE C.V');
INSERT INTO contactos VALUES('0992','COLUMBUS CXP','fsalazar@colind.net');
INSERT INTO contactos VALUES('0992','LILIANA RAMOS','lramos@colind.net');
INSERT INTO clientes VALUES('0993','SMITHS HEALTHCARE MANUFACTURING S.A. DE C.V.');
INSERT INTO contactos VALUES('0993','ALEJANDRO SALAS','alejandro.salas@smiths-medical.com');
INSERT INTO clientes VALUES('1016','BUEHLER MOTOR DE MÉXICO, S. DE R.L. DE C.V');
INSERT INTO contactos VALUES('1016','BUEHLER MOTOR DE MEXICO CXP','oleyda.mata@buehlermotor.com');
INSERT INTO clientes VALUES('1018','YACIMIENTOS Y DERIVADOS, S.A. DE C.V.');
INSERT INTO contactos VALUES('1018','GUILLERMO MARQUEZ','yacimientosyderivados1@hotmail.com');
INSERT INTO clientes VALUES('1025','COMPAÑIA DE OPERACIONES DE NITRÓGENO, S.A DE C.V');
INSERT INTO contactos VALUES('1025','CXC','Lindeus-invoice@banctec.com');
INSERT INTO contactos VALUES('1025','CXC','facturacion.consa.lg.mx@linde.com');
INSERT INTO clientes VALUES('1033','WERNER LADDER DE MÉXICO S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('1033','SOLIS','solisjm@wernerco.com');
INSERT INTO clientes VALUES('1034','MINERA SAN FRANCISCO DEL ORO S.A DE C.V');
INSERT INTO contactos VALUES('1034','PORTAL','cfd_frisco@condumex.com.mx');
INSERT INTO clientes VALUES('1037','COFLEX,S.A. DE C.V.');
INSERT INTO contactos VALUES('1037','ING PATRICIA JIMENEZ','pjimenez@coflex.com.mx');
INSERT INTO clientes VALUES('1038','MARTIN ENGINEERING MÉXICO, S. DE R.L DE C.V');
INSERT INTO contactos VALUES('1038','MARTIN ENGINEERING','gerardog@martin-eng.com');
INSERT INTO clientes VALUES('1046','GRUPO STONCOR S.A DE C.V');
INSERT INTO contactos VALUES('1046','GABRIELA TOVAR','gtovar@stoncor.com');
INSERT INTO clientes VALUES('1049','VALUACIÓN Y SERVICIOS INTEGRADOS S.A. DE C.V.');
INSERT INTO contactos VALUES('1049','JOSE GILBERTO','avalu0@hotmail.com');
INSERT INTO contactos VALUES('1049','JOSE GILBERTO','ca15122000@yahoo.com.mx');
INSERT INTO clientes VALUES('1050','MANSOUR MINING TECHNOLOGIES DE MEXICO SA DE CV');
INSERT INTO contactos VALUES('1050','FLOR GONZALEZ','f.gonzalez@mansourmining.com');
INSERT INTO contactos VALUES('1050','J HERRERA','jherrera@grupommm.com.mx');
INSERT INTO clientes VALUES('1051','HUNTING ENERGY DE MEXICO S DE RL DE CV');
INSERT INTO contactos VALUES('1051','ARTURO PIMENTEL','arturo.pimentel@hunting-intl.com');
INSERT INTO clientes VALUES('1055','DIA BRAS MEXICANA S.A. DE C.V.');
INSERT INTO contactos VALUES('1055','LUIS CHAVEZ','lcurtaza@diabras.com');
INSERT INTO clientes VALUES('1060','QUIMIPRODUCTOS, S.A DE C.V');
INSERT INTO contactos VALUES('1060','CUENTAS POR PAGAR','imelda.sanchez@efemsa.com');
INSERT INTO clientes VALUES('1062','QUESERÍA DOS LAGUNAS, S. PR. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('1062','QUESERÍA DOS LAGUNAS','erios@qdl.com.mx');
INSERT INTO clientes VALUES('1065','MEAD JOHNSON NUTRICIONALES DE MÉXICO, S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('1065','ALMA AGUIRRE','alma.aguirre@mjn.com');
INSERT INTO contactos VALUES('1065','ALMA AGUIRRE','alma.aguirre@mjn.com');
INSERT INTO contactos VALUES('1065','CXP','mjn1_MX_invoice_email@rapid.ihost.com');
INSERT INTO clientes VALUES('1068','ALMACENADORA ACCEL S.A');
INSERT INTO contactos VALUES('1068','ALMACENADORA','hharmon@accel.com.mx');
INSERT INTO contactos VALUES('1068','ALMACENADORA','lsiller@accel.com.mx');
INSERT INTO clientes VALUES('1094','KALISCHATARRA, S. DE R.L DE C.V');
INSERT INTO contactos VALUES('1094','KALISCHATARRA','ruben.acosta@kchatarra.com');
INSERT INTO clientes VALUES('1104','PEDRO FLORES CASTILLO');
INSERT INTO contactos VALUES('1104','PEDRO FLORES CASTILLO','pflores@helixts.com');
INSERT INTO clientes VALUES('1114','DANACHEMICALS S. DE R.L DE C.V');
INSERT INTO contactos VALUES('1114','DANACHEMICALS','danachemicals@yahoo.com.mx');
INSERT INTO clientes VALUES('1117','AGROSISTEMAS Y PROYECTOS S.A DE C.V.');
INSERT INTO contactos VALUES('1117','CXC','agrosistemasyproyectos@gmail.com');
INSERT INTO clientes VALUES('1132','TUBOS DE ACERO DE MÉXICO, S.A');
INSERT INTO contactos VALUES('1132','TUBOS DE ACERO DE MÉXICO','araceli.maldonado@tamsa.com.mx');
INSERT INTO clientes VALUES('1135','ROBOTICA EDUCATIVA DE MEXICO SA DE CV');
INSERT INTO contactos VALUES('1135','ROBOTICA EDUCATIVA DE MEXICO','aflores@roboticaeducativa.com.mx');
INSERT INTO clientes VALUES('1140','AUTOPARTES Y ARNESES DE MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('1140','AUTOPARTES Y ARNESES','laura.sosa@mx.yazaki.com.mx');
INSERT INTO contactos VALUES('1140','GABRIELA VALADEZ','gabriela.valadez@mx.yazaki.com');
INSERT INTO clientes VALUES('1141','UNIVERSIDAD TECNOLÓGICA METROPOLITANA');
INSERT INTO contactos VALUES('1141','THELMA NOVELO','tenovelo@hotmail.com');
INSERT INTO clientes VALUES('1147','ANALÍTICA DEL NOROESTE S.A DE C.V');
INSERT INTO contactos VALUES('1147','ANALÍTICA DEL NOROESTE  CXP','servicios@analiticadelnoroeste.com');
INSERT INTO clientes VALUES('1162','BLASS FLORES TRANSPORTISTAS SA. DE C.V');
INSERT INTO contactos VALUES('1162','BLASS FLORES TRANSPORTISTAS','anitaflowers@hotmail.com');
INSERT INTO contactos VALUES('1162','BLASS FLORES TRASPORTISTAS','aach001@hotmail.com');
INSERT INTO clientes VALUES('1168','ROBERT BOSCH, S. DE R.L DE C.V');
INSERT INTO contactos VALUES('1168','CXC','cuentasporpagar@us.bosch.com');
INSERT INTO contactos VALUES('1168','ROBERT BOSCH','external.cesar.frias@mx.bosch.com');
INSERT INTO contactos VALUES('1168','ROBERT BOSCH','alma.alarcon@mx.bosch.com');
INSERT INTO contactos VALUES('1168','ROBERT BOSCH','fabiola.rojas@mx.bosch.com');
INSERT INTO contactos VALUES('1168','ROBERT BOSCH','tip.ctg3payables@us.bosch.com');
INSERT INTO clientes VALUES('1170','JORGE CONTRERAS MUÑOZ');
INSERT INTO contactos VALUES('1170','JORGE CONTRERAS MUÑOZ','perlita_et@hotmail.com');
INSERT INTO clientes VALUES('1184','ILAS MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('1184','ILAS DE MEXICO','pmaldonado@renypicot.com.mx');
INSERT INTO clientes VALUES('1189','GRUPO ALTEX, S.A DE C.V');
INSERT INTO contactos VALUES('1189','CUENTAS POR PAGAR','dkawano@grupoaltex.com.mx');
INSERT INTO clientes VALUES('1191','ELECTRÓNICA DALE DE MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('1191','ANGELA CERVERA','angela.cervera@vishay,com');
INSERT INTO contactos VALUES('1191','ELECTRONICA DALE CXP','sandra.palomino@vishay.com');
INSERT INTO clientes VALUES('1192','TECSTAR DE MÉXICO, S.A DE C.V.');
INSERT INTO contactos VALUES('1192','TECSTAR DE MEXICO CXP','adriana.aguirre@mgstech.com');
INSERT INTO contactos VALUES('1192','TECSTAR DE MEXICO CXP','ana.pena@mgstech.com');
INSERT INTO clientes VALUES('1195','COMERCIALIZADORA Y DISTRIBUIDORA DE PRODUCTOS, BIENES Y SERVICIOS DE L');
INSERT INTO contactos VALUES('1195','COMERCIALIZADORA Y DISTRIBUCION DE PRODU','logisticaguzman@hotmail.com');
INSERT INTO clientes VALUES('1198','JUAN HÉCTOR SALGADO RAMÍREZ');
INSERT INTO contactos VALUES('1198','HÉCTOR SALGADO','jhectorsr1970@hotmail.com');
INSERT INTO clientes VALUES('1200','TRANSPORTADORA DE JUÁREZ, S.A DE C.V');
INSERT INTO contactos VALUES('1200','ELIZABETH CENICEROS','eceniceros@fuentes7.com.mx');
INSERT INTO contactos VALUES('1200','TRANSPORTADORA DE JUÁREZ','msanchez@fuentes7.com.mx');
INSERT INTO clientes VALUES('1201','AKSYS DE MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('1201','AKSYS CXP','iliana.garcilazo@apsolutions.com.mx');
INSERT INTO clientes VALUES('1202','DEMEK, S.A DE C.V');
INSERT INTO contactos VALUES('1202','DEMEK','facturas@demek.com');
INSERT INTO clientes VALUES('1204','WATER SERVICE TECHNOLOGIES');
INSERT INTO contactos VALUES('1204','WATER SERVICE TECHNOLOGIES','erodriguez@waterservicetech.com');
INSERT INTO clientes VALUES('1206','POCHTECA MATERIAS PRIMAS S.A DE C.V');
INSERT INTO contactos VALUES('1206','POCHTECA MATERIAS','hfloresa@pochteca.com.mx');
INSERT INTO clientes VALUES('1208','MUNICIPIO DE JIMENEZ');
INSERT INTO contactos VALUES('1208','MUNICIPIO DE JIMENEZ','tesoreriajimenez2010_2013@hotmail.com');
INSERT INTO contactos VALUES('1208','MUNICIPIO DE JIMENEZ','oficialia_jimenez@hotmail.com');
INSERT INTO contactos VALUES('1208','MUNICIPIO DE JIMENEZ','mariodelfines@hotmail.com');
INSERT INTO clientes VALUES('1210','MINERA CASCABEL S.A DE C.V');
INSERT INTO contactos VALUES('1210','MINERA CASCABEL','mineracascabel@hotmail.com');
INSERT INTO contactos VALUES('1210','MINERA CASCABEL','ernestomacho.2008@hotmail.com');
INSERT INTO clientes VALUES('1211','BN PRODUCTOS MAQUINADOS Y SINTERIZADOS DE MEXICO S DE RL DE CV');
INSERT INTO contactos VALUES('1211','ING. DEYANIRA CARDONA','deyanira.cardona@burgessnorton.com');
INSERT INTO clientes VALUES('1212','DANIEL MEASUREMENT AND CONTROL INC');
INSERT INTO contactos VALUES('1212','EDUARDO GONZALEZ','eduardo.gonzalez@emerson.com');
INSERT INTO contactos VALUES('1212','FACTURAS DLLS','daniel.invoice@emerson.com');
INSERT INTO clientes VALUES('1213','ASFALTOS DE LA FRONTERA S.A DE C.V');
INSERT INTO contactos VALUES('1213','ASFALTOS DE LA FRONTERA','nohemi@asfaltosdelafrontera.com.mx');
INSERT INTO clientes VALUES('1216','PRODUCTORA DE QUESOS SIERRA VERDE S.C.L.');
INSERT INTO contactos VALUES('1216','PRODUCTORA DE QUESOS SIERRA VERDE','facturacion@gruposierraverde.com');
INSERT INTO contactos VALUES('1216','PRODUCTORA DE QUESOS SIERRA VERDE','bernardo@gruposierraverde.com');
INSERT INTO clientes VALUES('1219','JORGE ALBERTO MIRELES VÁZQUEZ');
INSERT INTO contactos VALUES('1219','JORGE ALBERTO MIRELES','jorge.mireles@gmail.com');
INSERT INTO clientes VALUES('1220','ABRAM OLFERT KRAHN');
INSERT INTO contactos VALUES('1220','ABRAM OLFERT KRAHN','olfert@prodigy.net.mx');
INSERT INTO clientes VALUES('1221','FRISA FORJADOS S.A DE C.V');
INSERT INTO contactos VALUES('1221','FRISA','acobarrubias@frisa.com');
INSERT INTO contactos VALUES('1221','FRISA','arivera@frisa.com');
INSERT INTO contactos VALUES('1221','FRISA','jlsaucedo@frisa.com');
INSERT INTO clientes VALUES('1222','SERVICIOS DE TECNOLOGÍA DE ALIMENTOS Y NUTRICIÓN S. DE R.L M.I');
INSERT INTO contactos VALUES('1222','SERVICIO DE TECNOLOGIA DE ALIMENTOS','clientes@alimentosynutricion.com');
INSERT INTO clientes VALUES('1223','BIO TECH INDUSTRIES S.A DE C.V');
INSERT INTO contactos VALUES('1223','BIO TECH','biotech.cxpagar@gmail.com');
INSERT INTO clientes VALUES('1224','COMPAÑÍA AGRÍCOLA INDUSTRIAL SANTA ANA, S.A');
INSERT INTO contactos VALUES('1224','COMPAÑIA AGRICOLA INDUSTRIAL SANTA ANA','evalenzuela@santaana.com.gt');
INSERT INTO clientes VALUES('1226','HPP SYSTEMS DE MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('1226','CXP','cvadillo@hppelzer.com.mx');
INSERT INTO contactos VALUES('1226','HPP','yhernandez@hppelzer.com.mx');
INSERT INTO clientes VALUES('1227','IMPULSORA PROMOTORA DEL NORTE S.A DE C.V');
INSERT INTO contactos VALUES('1227','IMPOLSORA PROMOTORA DEL NORTE','cuentasporpagar@qualityinnchihuahua.com');
INSERT INTO clientes VALUES('1229','JOSE EDUARDO MILAN MONTENEGRO');
INSERT INTO contactos VALUES('1229','JOSE EDUARDO MILAN MONTENEGRO','recepcion@milec.com.mx');
INSERT INTO clientes VALUES('1231','DS SERVICIOS PETROLEROS S.A DE C.V.');
INSERT INTO contactos VALUES('1231','DS SERVICIOS PETROLEROS','jorgecastro@dssp.com.mx');
INSERT INTO clientes VALUES('1232','JTC TORNILLOS Y RESORTES SA DE CV');
INSERT INTO contactos VALUES('1232','GENARO SANCHEZ','jtccompras@tornillosyresortes.com');
INSERT INTO clientes VALUES('1233','SOPORTES Y SERVICIOS QUIMICOS SR SA DE CV');
INSERT INTO contactos VALUES('1233','SAM CRUZ','sam.cruz@ssqsr.com');
INSERT INTO clientes VALUES('1235','QUÍMICA BGEM S.A DE C.V');
INSERT INTO contactos VALUES('1235','HECTOR ROGELIO','hector.rogelio@biograssextra.com');
INSERT INTO clientes VALUES('1236','MAGNELEC, S.A DE C.V.');
INSERT INTO contactos VALUES('1236','LILIANA SANCHEZ','ap_qr@penoles.com.mx');
INSERT INTO clientes VALUES('1238','RENYSON DE MÉXICO S.A DE C.V.');
INSERT INTO contactos VALUES('1238','RENYSON','mchavira@renyson.com');
INSERT INTO clientes VALUES('1239','ELECTRO COMPONENTES DE MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('1239','GUILLERMO GUERRERO','guillermo.guerrero@ecintl.com');
INSERT INTO clientes VALUES('1243','MISSOURI STATE UNIVERSITY');
INSERT INTO contactos VALUES('1243','DR MELIDA GUTIERREZ','MGutierrez@missouristate.edu');
INSERT INTO clientes VALUES('1245','CLARIMEX S.A. DE C.V.');
INSERT INTO contactos VALUES('1245','CLARIMEX','mquiroz@clarimex.com');
INSERT INTO clientes VALUES('1246','FUNDICION AGUILAS S.A. DE C.V.');
INSERT INTO contactos VALUES('1246','E CANO','ecano@fundicionaguilas.com');
INSERT INTO contactos VALUES('1246','J GUERRERO','jguerrero@fundicionaguilas.com');
INSERT INTO clientes VALUES('1247','SINQUIMICA, S.A DE C.V.');
INSERT INTO contactos VALUES('1247','SINQUIMICA','calidad_sinquimica@quimia.com.mx');
INSERT INTO clientes VALUES('1250','HOME INTERIORS DE MÉXICO S. DE R.L. DE C.V.');
INSERT INTO contactos VALUES('1250','HOME INTERIORS','ccavazos@homeinteriors.com.mx');
INSERT INTO clientes VALUES('1251','JARA INGENIEROS Y ARQUITECTOS S.A DE C.V');
INSERT INTO contactos VALUES('1251','MANUEL JARA','mjarad10@gmail.com');
INSERT INTO clientes VALUES('1256','CHOVATEK SA DE CV');
INSERT INTO contactos VALUES('1256','JUAN CARLOS HERNÁNDEZ VARELA','jhernandez@thermotek.com.mx');
INSERT INTO clientes VALUES('1257','INDUSTRIAL BLOQUERA MEXICANA, S.A DE C.V');
INSERT INTO contactos VALUES('1257','INDUSTRIAL BLOQUERA MEXICANA','sistemaiso9001@industrialbloquera.com.mx');
INSERT INTO clientes VALUES('1258','MINAS STA MARÍA DE MORIS S.A. DE C.V.');
INSERT INTO contactos VALUES('1258','MINAS','julio.palma@hocplc.com');
INSERT INTO clientes VALUES('1261','SERVICIOS DE MANUFACTURA Y DESARROLLO S.A DE C.V');
INSERT INTO contactos VALUES('1261','CXC','Recepcion_CFD_shelter@intermex.com');
INSERT INTO clientes VALUES('1262','ARMENDARIZ MORAN CONSULTORES, S.C');
INSERT INTO contactos VALUES('1262','CARMEN MENDEZ','carmenml@armendariz-asociados.com.mx');
INSERT INTO clientes VALUES('1273','NELLCOR PURITAN BENNET MÉXICO, S.A DE C.V');
INSERT INTO contactos VALUES('1273','CXP','Yolanda.Mata@Covidien.com');
INSERT INTO clientes VALUES('1281','CENTRO DE INVESTIGACIÓN Y DOCENCIA ECONÓMICAS, A.C.');
INSERT INTO contactos VALUES('1281','JUAN MANUEL RAMIREZ','juanmanuel.ramirez@cide.edu');
INSERT INTO contactos VALUES('1281','JUAN MANUEL RAMIREZ','jmramriv@gmail.com');
INSERT INTO clientes VALUES('1304','INSTITUTO DE PEDAGOGÍA CRÍTICA, S.C.');
INSERT INTO contactos VALUES('1304','ROMELIA HINOJOSA','romehinojosa@hotmail.com');
INSERT INTO clientes VALUES('1305','DDR MEXICO, S.A. DE C.V.');
INSERT INTO contactos VALUES('1305','CARLOS FLORES','carlos.flores@ddrmexico.com');
INSERT INTO clientes VALUES('1306','TELÉFONOS DEL NOROESTE, S.A. DE C.V.');
INSERT INTO contactos VALUES('1306','GERARDO MORA','gemo@telnor.com');
INSERT INTO clientes VALUES('1392','DESARROLLO ECONOMICO DEL ESTADO DE CHIHUAHUA, A.C.');
INSERT INTO contactos VALUES('1392','CENIA SILVIA CHAPARRO','cenia.chaparro@desec.org.mx');
INSERT INTO clientes VALUES('1398','MARIA DEL ROSARIO BARAY GUERRERO');
INSERT INTO contactos VALUES('1398','MARIA DEL ROSARIO BARAY GUERRERO','rosariobaray@yahoo.com.mx');
INSERT INTO clientes VALUES('1409','INSTALACIONES Y DISEÑOS ELÉCTRICOS DE CHIHUAHUA, S. A DE C.V');
INSERT INTO contactos VALUES('1409','SANDRA HINOJOS','sandrahinojos@idechisa.com');
INSERT INTO clientes VALUES('1443','IIPROME S.A DE C.V.');
INSERT INTO contactos VALUES('1443','IIPROME','iiprome@prodigy.net.mx');
INSERT INTO clientes VALUES('1444','BRENDA MARIEL CERVANTES ESPINOZA');
INSERT INTO contactos VALUES('1444','JESUS RUBIO','alexrubio15@hotmail.com');
INSERT INTO clientes VALUES('1492','CONSTRUCTORA Y ACABADOS LERMA S.A DE C.V.');
INSERT INTO contactos VALUES('1492','CXC','pasgos@constructoralerma.com');


